name: candy_tracker
description: "A new Flutter project."
version: 1.2.0+3

environment:
  sdk: ^3.10.0

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^3.0.3
  formz: ^0.8.0
  geolocator: ^14.0.2
  go_router: ^16.2.0
  google_fonts: ^6.3.2
  google_maps_flutter: ^2.12.3
  image_picker: ^1.2.0
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  uuid: ^4.5.1

dev_dependencies:
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon.png"
  min_sdk_android: 24 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icon/
